# Directories and files to exclude from linting
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Maximum allowed line length
line-length = 88

# Number of spaces for indentation
indent-width = 4

# Target Python version for linting
target-version = "py312"

# Linting configuration section
[lint]
# Specific error codes to select for linting
select = ["E4", "E7", "E9", "F"]
# Error codes to ignore (none in this case)
ignore = []
# Error codes that can be automatically fixed
fixable = ["ALL"]
# Error codes that cannot be automatically fixed
unfixable = []
# Regular expression for identifying dummy variable names
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Formatting configuration section
[format]
# Preferred quote style for strings
quote-style = "double"
# Indentation style (space or tab)
indent-style = "space"
# Whether to skip magic trailing commas
skip-magic-trailing-comma = false
# Line ending style (auto-detect based on OS)
line-ending = "auto"
# Whether to format code blocks within docstrings
docstring-code-format = true
# Line length for code within docstrings
docstring-code-line-length = "dynamic"